/**
 * 初期登録フォームの学部・研究科一覧（Web/モバイル共通）。
 * 学部は学科の配列を持つ。研究科（大学院）は学科を持たないため空配列。
 */
import type { Language } from "./types/app";

export const FACULTIES: Record<Language, Record<string, string[]>> = {
  ja: {
    "文学部": ["人文学科"],
    "国際人間科学部": ["グローバル文化学科", "発達コミュニティ学科", "環境共生学科", "子ども教育学科"],
    "法学部": ["法律学科"],
    "経済学部": ["経済学科"],
    "経営学部": ["経営学科"],
    "理学部": ["数学科", "物理学科", "化学科", "生物学科", "惑星学科"],
    "医学部": ["医学科", "医療創生工学科", "保健学科"],
    "工学部": ["建築学科", "市民工学科", "電気電子工学科", "機械工学科", "応用化学科"],
    "システム情報学部": ["システム情報学科"],
    "農学部": ["食料環境システム学科", "資源生命科学科", "生命機能科学科"],
    "海洋政策科学部": ["海洋政策科学科"],
    "人文学研究科": [],
    "国際文化学研究科": [],
    "人間発達環境学研究科": [],
    "法学研究科": [],
    "経済学研究科": [],
    "経営学研究科": [],
    "理学研究科": [],
    "医学研究科": [],
    "保健学研究科": [],
    "工学研究科": [],
    "システム情報学研究科": [],
    "農学研究科": [],
    "海事科学研究科": [],
    "国際協力研究科": [],
    "科学技術イノベーション研究科": [],
  },
  en: {
    "Letters": ["Humanities"],
    "Global Human Sciences": ["Global Culture Studies", "Human Development", "Environmental Coexistence", "Child Education"],
    "Law": ["Law"],
    "Economics": ["Economics"],
    "Business Administration": ["Business Administration"],
    "Science": ["Mathematics", "Physics", "Chemistry", "Biology", "Planetology"],
    "Medicine": ["Medicine", "Medical Innovation and Engineering", "Health Sciences"],
    "Engineering": ["Architecture", "Civil Engineering", "Electrical and Electronic Engineering", "Mechanical Engineering", "Applied Chemistry"],
    "System Informatics": ["System Informatics"],
    "Agriculture": ["Food and Environmental Systems Science", "Resource Biological Sciences", "Life Science and Biotechnology"],
    "Maritime Policy Sciences": ["Maritime Policy Sciences"],
    "Graduate School of Humanities": [],
    "Graduate School of Intercultural Studies": [],
    "Graduate School of Human Development and Environment": [],
    "Graduate School of Law": [],
    "Graduate School of Economics": [],
    "Graduate School of Business Administration": [],
    "Graduate School of Science": [],
    "Graduate School of Medicine": [],
    "Graduate School of Health Sciences": [],
    "Graduate School of Engineering": [],
    "Graduate School of System Informatics": [],
    "Graduate School of Agricultural Science": [],
    "Graduate School of Maritime Sciences": [],
    "Graduate School of International Cooperation Studies": [],
    "Graduate School of Science, Technology and Innovation": [],
  },
};
